### ISSUE TITLE
Bad monetary mass (in UD)

### ISSUE THREAD

**Issue by blavenie** [duniter/duniter-ui#16]
On currency "sou", duniter-desktop show a monetary mass as "118773 UD" instead of 7 UD (1 UD / day)

![bug-duniter_monetary_mass](https://cloud.githubusercontent.com/assets/5269556/19184166/213eb57c-8c7c-11e6-884f-0de4a9e3ba28.png)

Under Cesium, value seems to be correct : 
![bug-duniter_monetary_mass-cesium_values](https://cloud.githubusercontent.com/assets/5269556/19184213/6027b9c8-8c7c-11e6-9da8-53d34941f3b4.png)

Any idea ?

**Comment by c-geek** [comment]
Yes, this is because the UD here is the "theoretical one", with the following data:

* [M = 24829016](http://duniter.le-sou.org:9600/blockchain/block/1209)
* [N = 31](http://duniter.le-sou.org:9600/blockchain/block/1209)
* [c = 0.000261](http://duniter.le-sou.org:9600/blockchain/parameters)

    UD = c * M / N
    UD = 0.000261 * 24829016 / 31
    UD = 209.044296

So we have M(UD) = 24829016 / 209.044296 = 118773 UD

But... your real UD currently *is not a cruising one*, so the c*M/N does not really apply. [Your current UD is 100208](http://duniter.le-sou.org:9600/blockchain/block/1209). So if we take the formula used in this version of Duniter:

    UD(t) = (1+c) UD(t-1)
    UD(t) = (1.000261) 100208
    UD(t) = 100234.1543

So you should have M(UD) = 24829016 / 100234.1543 ~= 247 UD

I will fix this.

**Comment by c-geek** [comment]
Moved to duniter/duniter#648.

**Comment by c-geek** [comment]
Fixed in b63bce0127c783aa97ca6f64e02c445ffc833c30
